import { CourseCurriculum } from './types';

export const COURSE_CURRICULA: Record<string, CourseCurriculum> = {
  'ai-education': {
    methodology: [
      { en: 'Short demonstrations followed by guided practice on participants’ own subjects and age groups.', es: 'Demostraciones breves seguidas de práctica guiada sobre las materias y etapas del propio profesorado.' },
      { en: 'Peer review with practical criteria for accuracy, bias, privacy and classroom value.', es: 'Revisión entre iguales con criterios prácticos de precisión, sesgos, privacidad y valor para el aula.' },
      { en: 'A personal classroom plan refined each day and ready to test after the course.', es: 'Un plan personal de aula que se mejora cada día y queda listo para probar tras el curso.' }
    ],
    dailyProgramme: [
      { title: { en: 'Starting with sound judgement', es: 'Empezar con criterio' }, focus: { en: 'What AI can and cannot do for everyday teaching.', es: 'Qué puede y qué no puede hacer la IA en el trabajo docente cotidiano.' }, activities: [{ en: 'Map repetitive tasks and identify worthwhile uses.', es: 'Mapear tareas repetitivas e identificar usos que realmente aportan valor.' }, { en: 'Compare AI responses with teacher-made examples.', es: 'Comparar respuestas de IA con ejemplos elaborados por docentes.' }], takeaway: { en: 'A personal decision framework for using AI.', es: 'Un marco personal para decidir cuándo usar IA.' } },
      { title: { en: 'Planning and resource design', es: 'Planificación y diseño de recursos' }, focus: { en: 'Prompts, lesson sequences and adaptable teaching materials.', es: 'Prompts, secuencias didácticas y materiales adaptables.' }, activities: [{ en: 'Create a lesson outline from a real curriculum goal.', es: 'Crear un esquema de sesión a partir de un objetivo curricular real.' }, { en: 'Build differentiated texts, examples and questions.', es: 'Crear textos, ejemplos y preguntas diferenciadas.' }], takeaway: { en: 'A reusable prompt and resource template pack.', es: 'Un paquete reutilizable de prompts y plantillas de recursos.' } },
      { title: { en: 'Inclusion and adaptation', es: 'Inclusión y adaptación' }, focus: { en: 'Using AI to offer multiple pathways without lowering expectations.', es: 'Usar IA para ofrecer distintos caminos sin bajar expectativas.' }, activities: [{ en: 'Adapt one activity for reading, language or attention needs.', es: 'Adaptar una actividad para necesidades de lectura, lengua o atención.' }, { en: 'Check accessibility, tone and cognitive load.', es: 'Revisar accesibilidad, tono y carga cognitiva.' }], takeaway: { en: 'An adapted classroom activity with an inclusion checklist.', es: 'Una actividad de aula adaptada con lista de comprobación inclusiva.' } },
      { title: { en: 'Assessment and feedback', es: 'Evaluación y retroalimentación' }, focus: { en: 'Feedback, rubrics and assessment tasks that remain teacher-led.', es: 'Retroalimentación, rúbricas y tareas de evaluación que siguen lideradas por el docente.' }, activities: [{ en: 'Draft success criteria and a feedback bank.', es: 'Diseñar criterios de éxito y un banco de retroalimentación.' }, { en: 'Test how to verify and personalise generated feedback.', es: 'Probar cómo verificar y personalizar la retroalimentación generada.' }], takeaway: { en: 'A reviewed feedback workflow for one real task.', es: 'Un flujo de feedback revisado para una tarea real.' } },
      { title: { en: 'Responsible implementation', es: 'Implementación responsable' }, focus: { en: 'Privacy, ethics, school agreements and a first implementation cycle.', es: 'Privacidad, ética, acuerdos de centro y un primer ciclo de implementación.' }, activities: [{ en: 'Work through classroom scenarios involving data and bias.', es: 'Resolver casos de aula sobre datos y sesgos.' }, { en: 'Present and improve a personal action plan.', es: 'Presentar y mejorar un plan de acción personal.' }], takeaway: { en: 'A 30-day responsible AI action plan.', es: 'Un plan de acción de IA responsable para 30 días.' } }
    ]
  },
  'inclusion-sen': {
    methodology: [
      { en: 'Case-based workshops drawn from everyday classroom barriers, not deficit labels.', es: 'Talleres basados en barreras cotidianas del aula, no en etiquetas de déficit.' },
      { en: 'Collaborative redesign of real activities, materials and assessment tasks.', es: 'Rediseño colaborativo de actividades, materiales y tareas de evaluación reales.' },
      { en: 'Reflection, peer feedback and a small-scale plan for transfer to school.', es: 'Reflexión, feedback entre iguales y un plan de transferencia al centro a pequeña escala.' }
    ],
    dailyProgramme: [
      { title: { en: 'Seeing barriers, not labels', es: 'Ver barreras, no etiquetas' }, focus: { en: 'How classroom routines can widen or reduce participation.', es: 'Cómo las rutinas de aula pueden ampliar o reducir la participación.' }, activities: [{ en: 'Map participation barriers in a typical lesson.', es: 'Mapear barreras de participación en una sesión habitual.' }, { en: 'Analyse learner variability through classroom cases.', es: 'Analizar la variabilidad del alumnado mediante casos de aula.' }], takeaway: { en: 'A barrier map for one teaching context.', es: 'Un mapa de barreras para un contexto docente.' } },
      { title: { en: 'Designing multiple pathways', es: 'Diseñar caminos múltiples' }, focus: { en: 'Universal Design for Learning as a practical planning tool.', es: 'El Diseño Universal para el Aprendizaje como herramienta práctica de planificación.' }, activities: [{ en: 'Apply engagement, representation and action principles.', es: 'Aplicar principios de implicación, representación y acción.' }, { en: 'Redesign a lesson with meaningful choices.', es: 'Rediseñar una sesión con opciones significativas.' }], takeaway: { en: 'A UDL-informed lesson outline.', es: 'Un esquema de sesión basado en DUA.' } },
      { title: { en: 'Accessible resources and routines', es: 'Recursos y rutinas accesibles' }, focus: { en: 'Language, visuals, instructions and assistive supports.', es: 'Lenguaje, elementos visuales, instrucciones y apoyos de acceso.' }, activities: [{ en: 'Audit a worksheet or digital resource for accessibility.', es: 'Auditar una ficha o recurso digital desde la accesibilidad.' }, { en: 'Create clearer instructions and scaffolded supports.', es: 'Crear instrucciones más claras y apoyos graduados.' }], takeaway: { en: 'An improved resource and accessibility checklist.', es: 'Un recurso mejorado y una lista de comprobación de accesibilidad.' } },
      { title: { en: 'Assessment that includes', es: 'Una evaluación que incluye' }, focus: { en: 'Evidence of learning through varied, rigorous formats.', es: 'Evidencias de aprendizaje mediante formatos variados y rigurosos.' }, activities: [{ en: 'Separate the learning goal from avoidable task barriers.', es: 'Separar el objetivo de aprendizaje de barreras evitables de la tarea.' }, { en: 'Design options for demonstrating understanding.', es: 'Diseñar opciones para demostrar comprensión.' }], takeaway: { en: 'An inclusive assessment adjustment.', es: 'Un ajuste de evaluación inclusiva.' } },
      { title: { en: 'From one lesson to school practice', es: 'De una sesión a la práctica de centro' }, focus: { en: 'Priorities, collaboration and realistic next steps.', es: 'Prioridades, colaboración y próximos pasos realistas.' }, activities: [{ en: 'Discuss cases and receive peer feedback.', es: 'Debatir casos y recibir feedback de compañeros.' }, { en: 'Set one classroom and one team commitment.', es: 'Definir un compromiso de aula y otro de equipo.' }], takeaway: { en: 'A short inclusion action plan.', es: 'Un breve plan de acción inclusiva.' } }
    ]
  },
  'digital-citizenship': {
    methodology: [
      { en: 'Inquiry-based work with current digital scenarios, images, headlines and platforms.', es: 'Trabajo indagativo con escenarios digitales actuales, imágenes, titulares y plataformas.' },
      { en: 'Collaborative verification and dialogue protocols that can be reused with students.', es: 'Protocolos colaborativos de verificación y diálogo reutilizables con el alumnado.' },
      { en: 'Design challenges culminating in a classroom-ready media-literacy activity.', es: 'Retos de diseño que culminan en una actividad de alfabetización mediática lista para el aula.' }
    ],
    dailyProgramme: [
      { title: { en: 'The digital world students inhabit', es: 'El mundo digital que habita el alumnado' }, focus: { en: 'Participation, identity, attention and digital habits.', es: 'Participación, identidad, atención y hábitos digitales.' }, activities: [{ en: 'Map real dilemmas from school life.', es: 'Mapear dilemas reales de la vida escolar.' }, { en: 'Identify skills students need to participate responsibly.', es: 'Identificar habilidades para participar de forma responsable.' }], takeaway: { en: 'A starting map of digital citizenship priorities.', es: 'Un mapa inicial de prioridades de ciudadanía digital.' } },
      { title: { en: 'Sources and verification', es: 'Fuentes y verificación' }, focus: { en: 'How to slow down, question and check information.', es: 'Cómo detenerse, cuestionar y comprobar información.' }, activities: [{ en: 'Use a simple verification protocol on real examples.', es: 'Usar un protocolo sencillo de verificación con ejemplos reales.' }, { en: 'Design questions that make source evaluation visible.', es: 'Diseñar preguntas que hagan visible la evaluación de fuentes.' }], takeaway: { en: 'A classroom verification routine.', es: 'Una rutina de verificación para el aula.' } },
      { title: { en: 'AI, images and evidence', es: 'IA, imágenes y evidencias' }, focus: { en: 'Critical reading of synthetic and manipulated content.', es: 'Lectura crítica de contenido sintético y manipulado.' }, activities: [{ en: 'Compare authentic, edited and AI-generated examples.', es: 'Comparar ejemplos auténticos, editados y generados por IA.' }, { en: 'Plan an age-appropriate AI literacy task.', es: 'Planificar una tarea de alfabetización en IA adecuada a la edad.' }], takeaway: { en: 'An AI and media literacy activity.', es: 'Una actividad de alfabetización en IA y medios.' } },
      { title: { en: 'Safety, privacy and wellbeing', es: 'Seguridad, privacidad y bienestar' }, focus: { en: 'Practical prevention without alarmism.', es: 'Prevención práctica sin alarmismo.' }, activities: [{ en: 'Work through privacy and communication scenarios.', es: 'Trabajar escenarios de privacidad y comunicación.' }, { en: 'Create classroom agreements for digital wellbeing.', es: 'Crear acuerdos de aula para el bienestar digital.' }], takeaway: { en: 'A set of age-appropriate discussion prompts.', es: 'Un conjunto de preguntas de diálogo adaptadas a la edad.' } },
      { title: { en: 'A project for responsible participation', es: 'Un proyecto de participación responsable' }, focus: { en: 'Bringing critical thinking, creativity and participation together.', es: 'Unir pensamiento crítico, creatividad y participación.' }, activities: [{ en: 'Prototype a student-facing campaign or inquiry.', es: 'Prototipar una campaña o indagación dirigida al alumnado.' }, { en: 'Give peer feedback using impact criteria.', es: 'Dar feedback entre iguales usando criterios de impacto.' }], takeaway: { en: 'A ready-to-run classroom project.', es: 'Un proyecto de aula listo para poner en marcha.' } }
    ]
  },
  'europe-classroom': {
    methodology: [
      { en: 'Collaborative project design rooted in participants’ school realities.', es: 'Diseño colaborativo de proyectos basado en la realidad de los centros participantes.' },
      { en: 'Structured intercultural exchange, dialogue and peer feedback.', es: 'Intercambio intercultural estructurado, diálogo y feedback entre iguales.' },
      { en: 'A final project canvas that makes transfer to classroom or school team explicit.', es: 'Un lienzo final de proyecto que hace explícita la transferencia al aula o al equipo de centro.' }
    ],
    dailyProgramme: [
      { title: { en: 'A European question for the classroom', es: 'Una pregunta europea para el aula' }, focus: { en: 'Shared challenges, local perspectives and meaningful questions.', es: 'Retos compartidos, perspectivas locales y preguntas significativas.' }, activities: [{ en: 'Exchange school contexts and learner priorities.', es: 'Intercambiar contextos de centro y prioridades del alumnado.' }, { en: 'Frame a question that connects local and European life.', es: 'Formular una pregunta que conecte vida local y europea.' }], takeaway: { en: 'A project question with European relevance.', es: 'Una pregunta de proyecto con relevancia europea.' } },
      { title: { en: 'Collaborative learning design', es: 'Diseño de aprendizaje colaborativo' }, focus: { en: 'Roles, tasks and evidence in project-based learning.', es: 'Roles, tareas y evidencias en el aprendizaje basado en proyectos.' }, activities: [{ en: 'Build a project sequence with clear learner roles.', es: 'Construir una secuencia de proyecto con roles claros.' }, { en: 'Plan collaboration that makes every contribution visible.', es: 'Planificar una colaboración que haga visible cada contribución.' }], takeaway: { en: 'A collaborative learning sequence.', es: 'Una secuencia de aprendizaje colaborativo.' } },
      { title: { en: 'Dialogue and participation', es: 'Diálogo y participación' }, focus: { en: 'Creating respectful spaces for different voices and perspectives.', es: 'Crear espacios respetuosos para voces y perspectivas diversas.' }, activities: [{ en: 'Practise dialogue protocols and facilitation moves.', es: 'Practicar protocolos de diálogo y estrategias de facilitación.' }, { en: 'Adapt an activity for intercultural participation.', es: 'Adaptar una actividad para la participación intercultural.' }], takeaway: { en: 'A facilitation guide for one classroom dialogue.', es: 'Una guía de facilitación para un diálogo de aula.' } },
      { title: { en: 'From exchange to partnership', es: 'Del intercambio a la colaboración' }, focus: { en: 'Sharing practice, documenting learning and finding common ground.', es: 'Compartir prácticas, documentar aprendizaje y encontrar terreno común.' }, activities: [{ en: 'Present a practice from each school context.', es: 'Presentar una práctica de cada contexto escolar.' }, { en: 'Identify simple opportunities for follow-up collaboration.', es: 'Identificar oportunidades sencillas de colaboración posterior.' }], takeaway: { en: 'A map of shared practices and possible links.', es: 'Un mapa de prácticas compartidas y posibles vínculos.' } },
      { title: { en: 'A project ready to transfer', es: 'Un proyecto listo para transferir' }, focus: { en: 'Turning the week into a feasible classroom or school initiative.', es: 'Convertir la semana en una iniciativa viable de aula o centro.' }, activities: [{ en: 'Complete a project canvas with milestones and evidence.', es: 'Completar un lienzo de proyecto con hitos y evidencias.' }, { en: 'Receive feedback and define first steps.', es: 'Recibir feedback y definir los primeros pasos.' }], takeaway: { en: 'A European classroom project canvas.', es: 'Un lienzo de proyecto europeo para el aula.' } }
    ]
  },
  'green-classroom': {
    methodology: [
      { en: 'Place-based and experiential learning connected to the local environment.', es: 'Aprendizaje situado y experiencial conectado con el entorno local.' },
      { en: 'Project design that links curriculum, student voice and feasible action.', es: 'Diseño de proyectos que une currículo, voz del alumnado y acción viable.' },
      { en: 'Reflection on evidence, impact and transfer rather than one-off activities.', es: 'Reflexión sobre evidencias, impacto y transferencia, no actividades aisladas.' }
    ],
    dailyProgramme: [
      { title: { en: 'Sustainability starts with questions', es: 'La sostenibilidad empieza con preguntas' }, focus: { en: 'Connecting global challenges with learners’ immediate surroundings.', es: 'Conectar retos globales con el entorno inmediato del alumnado.' }, activities: [{ en: 'Identify curriculum links and local environmental questions.', es: 'Identificar conexiones curriculares y preguntas ambientales locales.' }, { en: 'Explore systems thinking through a shared case.', es: 'Explorar el pensamiento sistémico mediante un caso compartido.' }], takeaway: { en: 'A local-to-global inquiry question.', es: 'Una pregunta de indagación de lo local a lo global.' } },
      { title: { en: 'Learning from place', es: 'Aprender del lugar' }, focus: { en: 'Observation, data and stories from the nearby environment.', es: 'Observación, datos e historias del entorno cercano.' }, activities: [{ en: 'Plan an outdoor or place-based learning sequence.', es: 'Planificar una secuencia de aprendizaje al aire libre o situada.' }, { en: 'Use simple observation and documentation tools.', es: 'Usar herramientas sencillas de observación y documentación.' }], takeaway: { en: 'A place-based learning plan.', es: 'Un plan de aprendizaje situado.' } },
      { title: { en: 'Experience, investigate, create', es: 'Experimentar, investigar, crear' }, focus: { en: 'Experiential methods that make learners active investigators.', es: 'Métodos experienciales que convierten al alumnado en investigador activo.' }, activities: [{ en: 'Prototype a field task or classroom investigation.', es: 'Prototipar una tarea de campo o investigación de aula.' }, { en: 'Design prompts for reflection and evidence.', es: 'Diseñar preguntas para reflexión y evidencias.' }], takeaway: { en: 'A student investigation toolkit.', es: 'Un kit de investigación para el alumnado.' } },
      { title: { en: 'Action with the community', es: 'Acción con la comunidad' }, focus: { en: 'Projects that are proportionate, collaborative and visible.', es: 'Proyectos proporcionados, colaborativos y visibles.' }, activities: [{ en: 'Define stakeholders and a realistic school action.', es: 'Definir agentes implicados y una acción escolar realista.' }, { en: 'Plan communication beyond the classroom.', es: 'Planificar comunicación más allá del aula.' }], takeaway: { en: 'A community-linked project outline.', es: 'Un esquema de proyecto vinculado a la comunidad.' } },
      { title: { en: 'Sustaining the learning', es: 'Sostener el aprendizaje' }, focus: { en: 'Evaluation, student voice and next steps.', es: 'Evaluación, voz del alumnado y próximos pasos.' }, activities: [{ en: 'Set evidence of learning and impact indicators.', es: 'Definir evidencias de aprendizaje e indicadores de impacto.' }, { en: 'Share action plans and refine them with peers.', es: 'Compartir planes de acción y afinarlos con compañeros.' }], takeaway: { en: 'A green classroom action plan.', es: 'Un plan de acción de aula verde.' } }
    ]
  },
  'wellbeing-teachers': {
    methodology: [
      { en: 'Practical, educational and preventive work; it is not therapy or clinical intervention.', es: 'Trabajo práctico, educativo y preventivo; no es terapia ni intervención clínica.' },
      { en: 'Reflection tools, scenarios and peer exchange focused on controllable school practices.', es: 'Herramientas de reflexión, escenarios e intercambio entre iguales centrados en prácticas escolares controlables.' },
      { en: 'Small, realistic action planning for personal routines and school climate.', es: 'Planificación de acciones pequeñas y realistas para rutinas personales y clima de centro.' }
    ],
    dailyProgramme: [
      { title: { en: 'Understanding the working context', es: 'Comprender el contexto de trabajo' }, focus: { en: 'Wellbeing, workload and school conditions through an educational lens.', es: 'Bienestar, carga de trabajo y condiciones escolares desde una mirada educativa.' }, activities: [{ en: 'Map energy drains and protective factors at work.', es: 'Mapear factores que desgastan y factores protectores en el trabajo.' }, { en: 'Distinguish individual habits from organisational conditions.', es: 'Distinguir hábitos individuales de condiciones organizativas.' }], takeaway: { en: 'A personal and contextual wellbeing map.', es: 'Un mapa personal y contextual de bienestar.' } },
      { title: { en: 'Workload and boundaries', es: 'Carga de trabajo y límites' }, focus: { en: 'Priorities, routines and communication that protect attention.', es: 'Prioridades, rutinas y comunicación que protegen la atención.' }, activities: [{ en: 'Review one weekly workflow for unnecessary friction.', es: 'Revisar un flujo semanal para detectar fricción innecesaria.' }, { en: 'Practise concise boundary-setting language.', es: 'Practicar un lenguaje breve para establecer límites.' }], takeaway: { en: 'A sustainable weekly routine experiment.', es: 'Un experimento de rutina semanal sostenible.' } },
      { title: { en: 'Communication and regulation', es: 'Comunicación y regulación' }, focus: { en: 'Responding constructively in demanding school situations.', es: 'Responder de forma constructiva en situaciones escolares exigentes.' }, activities: [{ en: 'Work through communication scenarios.', es: 'Trabajar escenarios de comunicación.' }, { en: 'Use short reflection and reset routines.', es: 'Usar rutinas breves de reflexión y reajuste.' }], takeaway: { en: 'A practical communication toolkit.', es: 'Un kit práctico de comunicación.' } },
      { title: { en: 'Positive classroom and school climate', es: 'Clima positivo de aula y centro' }, focus: { en: 'Belonging, expectations and collaborative routines.', es: 'Pertenencia, expectativas y rutinas colaborativas.' }, activities: [{ en: 'Audit a classroom or team routine for climate impact.', es: 'Auditar una rutina de aula o equipo por su impacto en el clima.' }, { en: 'Design a small practice that strengthens belonging.', es: 'Diseñar una práctica pequeña que refuerce la pertenencia.' }], takeaway: { en: 'A positive climate micro-intervention.', es: 'Una microintervención de clima positivo.' } },
      { title: { en: 'A plan that can last', es: 'Un plan que puede durar' }, focus: { en: 'Choosing fewer actions, measuring progress and seeking support.', es: 'Elegir menos acciones, medir avances y buscar apoyo.' }, activities: [{ en: 'Build a 30-day personal or team plan.', es: 'Construir un plan personal o de equipo para 30 días.' }, { en: 'Give and receive supportive peer feedback.', es: 'Dar y recibir feedback de apoyo entre iguales.' }], takeaway: { en: 'A realistic wellbeing and climate action plan.', es: 'Un plan realista de bienestar y clima escolar.' } }
    ]
  }
};
